// src/core/types/audio.ts
export type AudioNode =
  | GainNode
  | OscillatorNode
  | AudioBufferSourceNode
  | BiquadFilterNode
  | StereoPannerNode
  | AnalyserNode
  | ConvolverNode
  | DelayNode
  | DynamicsCompressorNode
  | WaveShaperNode
  | MediaElementAudioSourceNode
  | MediaStreamAudioSourceNode
  | ChannelSplitterNode
  | ChannelMergerNode
  | IIRFilterNode
  | ConstantSourceNode
  | PannerNode
  | AudioWorkletNode
  | AudioDestinationNode;
